name: "Lint & Test PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    name: Pint, Rector & Test with coverage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        php: [ 8.3, 8.4 ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Check PR title"
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: xdebug

      - name: "Install Composer Dependencies"
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader --no-ansi --no-progress

      - name: Prepare Laravel
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.20

      - name: Install bun dependencies
        run: bun update

      - name: Build manifest
        run: bun run build

      - name: "Run Rector"
        run: |
          ./vendor/bin/rector process --dry-run --config=rector.php

      - name: "Run Pint"
        run: |
          ./vendor/bin/pint --config=pint.json --test --verbose --dirty

      - name: "Run Tests"
        run: |
          ./vendor/bin/pest --colors=always --stop-on-failure --coverage --ci
